name: 🧪 Lint, Test & Check Coverage 🧐

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    name: Test the build
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v2"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm install
    - name: Lint, Test & Coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage